### ISSUE TITLE
ToC for Slack Channels

### ISSUE THREAD

**Issue by zkat** [WeAllJS/wealljs.github.io#13]
It would be nice to have a general table of contents for all the slack channels, structured and grouped by useful categories. This should include all the known (toplevel) identity channels, along with instructions to `/admin` in order to get invites to them and a pointer that some of those identity channels have private sub-resource-channels (but idk if we should necessarily list those).

**Comment by jenniferlynparsons** [comment]
Is this still something that's wanted?

**Comment by zkat** [comment]
Nah. I think we're all set on this front, tbh. Closing.
