### ISSUE TITLE
Culture and Process page needs some CSS love.

### ISSUE THREAD

**Issue by lewiscowper** [WeAllJS/wealljs.github.io#5]
For context [here is the current state](http://wealljs.org/culture-and-process)

I'm willing to add some styles to make this more readable and less raw HTML-y if I can just figure out where I can add them where they'll be picked up.

**Comment by hbarudin** [comment]
Link in PR is malformed? Do you mean http://wealljs.org/culture-and-process ?

**Comment by lewiscowper** [comment]
Ah, my bad, most probably yes! Sorry 😱

**Comment by zkat** [comment]
@lewiscowper this would be great! I'll direct people interested in doing CSS stuff with those pages over here.

I think the main thing that needs to be done is for `index.html` to be extracted into a [`_layouts/default.html`](https://jekyllrb.com/docs/structure/) layout (search for `_layouts`) that the individual pages can then include. Then the CoC/enforcement/culture pages can all use have a `layout: default` and they'll Just Work™.
